version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/app
    file_exists_behavior: OVERWRITE
permissions:
  - object: /home/ubuntu/app
    pattern: "**"
    owner: ubuntu
    group: ubuntu
    mode: 755
  - object: /home/ubuntu/app/scripts
    pattern: "**"
    owner: ubuntu
    group: ubuntu
    mode: 755
    type:
      - file
hooks:
  BeforeInstall:
    - location: scripts/stop_application.sh
      timeout: 180
      runas: ubuntu
      on_failure: CONTINUE
  AfterInstall:
    - location: scripts/install.sh
      timeout: 600
      runas: ubuntu
      on_failure: STOP_DEPLOYMENT
  ApplicationStart:
    - location: scripts/start_application.sh
      timeout: 300
      runas: ubuntu
      on_failure: STOP_DEPLOYMENT
  ApplicationStop:
    - location: scripts/stop_application.sh
      timeout: 180
      runas: ubuntu
      on_failure: CONTINUE
  ValidateService:
    - location: scripts/validate_service.sh
      timeout: 400
      runas: ubuntu
      on_failure: STOP_DEPLOYMENT